name: docker-ci.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t practica-app:ci .

      - name: Show Docker image size
        run: |
          IMAGE_SIZE_BYTES=$(docker image inspect practica-app:ci --format='{{.Size}}')
          echo "Image size: ${IMAGE_SIZE_BYTES} bytes"
          echo "Image size human readable: $(numfmt --to=iec --suffix=B ${IMAGE_SIZE_BYTES})"