name: PR Validation

on:
  pull_request:
    branches:
      [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^[0-9]+-[a-zA-Z0-9-]+$ ]]; then
            echo "Invalid branch name. Please use the format '123-feature-name'."
            exit 1
          fi

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
